### ISSUE TITLE
digicamscheduling-elevation does not print schedule in terminal

### ISSUE THREAD

**Issue by dneise** [calispac/digicam_scheduling#4]
In the TRAC here:

http://ui.cta.camk.edu.pl/trac/wiki/SST1Mshift#Generatingandloadingtheobservationschedule

it says:
 4- Look at the plot you have just produced (stored in the figures/ directory) and check whether it matches the text output and the decision taken during the meeting.
5- Once you have verified that the schedule is ok copy the schedule that was printed in the terminal
6- Open the GUI and copy the schedule on the master schedule.

I am executing the current master, I just checked out 5min ago and this version does not print anything in the terminal

**Comment by calispac** [comment]
Sorry for the confusion... I think the wiki got I bit messed up while I was editing at the same time as someone else

**Comment by dneise** [comment]
No need to be sorry, just wanted to inform you.

Also, I cannot edit the wiki, so there was no quick way for me to fix this.

**Comment by calispac** [comment]
:+1: 
To print the schedule I planned to make a second script that would be called with the same arguments as the one to make the elavation plots. I will soon have it done.

**Comment by calispac** [comment]
I think this is solved now. And the wiki is updated
