### ISSUE TITLE
font warning from matplotlib

### ISSUE THREAD

**Issue by dneise** [calispac/digicam_scheduling#5]
getting this warning when doing e.g. this call:

    digicamscheduling-elevation --start_date='2018-08-07 18:00' --end_date='2018-08-08 10:00' --time_step=1 --output_path='figures/' --show

```
/home/dneise/anaconda3-5.1.0/lib/python3.6/site-packages/matplotlib/font_manager.py:1320: UserWarning: findfont: Font family ['serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

**Comment by calispac** [comment]
I don't know how to solve this properly. Maybe we should just edit the matplotlibrc file to not use this particular font
