### ISSUE TITLE
How to avoid creating PNGs?

### ISSUE THREAD

**Issue by dneise** [calispac/digicam_scheduling#6]
When doing this call:

    digicamscheduling-elevation --start_date='2018-08-07 18:00' --end_date='2018-08-08 10:00'  --show

I get PNGs created in the current dir. Should it be possible to avoid creating the PNGs at all, in case one only wants to have a quick look at the plots?

**Comment by calispac** [comment]
I could just make that using `--show` does not save figures. Or that if the `--output` is not specified then nothing is saved

**Comment by dneise** [comment]
sounds good
