### ISSUE TITLE
moon deactivation

### ISSUE THREAD

**Issue by sliusar** [calispac/digicam_scheduling#8]
Cyril, how to disable moon phase consideration in digicamscheduling? I cannot use custom catalog of stars to check their visibility due to that, I specify catalog as  --sources_filename=digicamscheduling/config/catalog_stars.txt , it is parsed correctly but visibility is zero for all stars.

I tried to comments last two "observability = " lines in core/environment.py, but apparently it is taken into account somewhere else, so no change.

Actually since moon affects all sources it is better not to decrease visibility of all sources all together but rather highlight the time span when moon affects them, for instance with different shades of grey depending on moon illumination, and red when it is > 85%

**Comment by yrenier** [comment]
i succeed to deactivate the moon by modifying line 67 of digicamschedueling/script/elevation.py
` moon_phase = moon.compute_moon_phase(date=date)*0`

**Comment by calispac** [comment]
This is solved in #7. Now you can call `digicam-elevation` with `--use_moon` option if you want to have moon phase and elevation taken into account of source visibility (by default it does not).

 > I tried to comments last two "observability = " lines in core/environment.py, but apparently it is taken into account somewhere else, so no change.

It should have actually work but it is probably because you did not reinstall the package. While running `python setup.py install` it creates the executables that can be called with `digicamscheduling-*

**Comment by calispac** [comment]
Once it is merged I can update it to the camera server. Some changes into the catalog were done (i.e. json files rather than .txt files). This means that your catalog probably does not work anymore. 

> Actually since moon affects all sources it is better not to decrease visibility of all sources all together but rather highlight the time span when moon affects them, for instance with different shades of grey depending on moon illumination, and red when it is > 85%

Thanks, I will play with color opacity.
